server:
  port: 8001

zuul:  routes:     coupon:
       url: http://localhost:8081
     admin :
       url: http://localhost:8082
     customer:
       url:  http://localhost:8083   
     login:
       url:  http://localhost:8084   
     company:  
       url: http://localhost:8085
    
management:  endpoints:    web:      exposure:        include: '*'
  endpoint:    health:      show-details: ALWAYS