server:
  port: 8001


zuul:  routes:     coupon:
       url: http://localhost:8081/coupon/
     admin :
       url: http://localhost:8082/admin/
     users:
       url:  http://localhost:8083/users/   
     company:  
       url: http://localhost:8085/company/
    
management:  endpoints:    web:      exposure:        include: '*'
  endpoint:    health:      show-details: ALWAYS